Repository canonical/charmed-osm.com, pull requests merged in 2019-11, with the labels that each got.

#3 Update CircleCI config
  .circleci/config.yml
Labels: Review: Code +1

#2 Add index page
  package.json
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/base.html
  templates/contact-us/index.html
  templates/contact-us/thank-you.html
  templates/index.html
  templates/partial/_footer.html
  templates/partial/_navigation.html
  templates/partial/_thank-you.html
  templates/thank-you.html
  tests/test_routes.py
  webapp/app.py
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#5 update Juju logo
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#6 Drops tutorial link for now
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#7 Links to the tutorial
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#9 Update index page to match copy doc
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#10 Adding tag manager
  templates/base.html
Labels: Review: Code +1, Review: QA +1

#12 Update vertical spacing in the integration section
  .github/pull_request_template.md
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#13 Update favicon image
  templates/base.html
Labels: Review: QA +1
